version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: greenthumb_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  client:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
volumes:
  pgdata:
